services:
  jenkins:
    #image: jenkins/jenkins:lts
    build: ./jenkins    
    container_name: jenkins-main
    ports:
      - "8080:8080"  # Puerto de Jenkins
      - "50000:50000" # Puerto de agente de Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
     
    networks:
      - project_network

    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  backend:     
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=Pruebas
      - PGPASSWORD=Pruebas4321*
      - PGDATABASE=mydatabase
    
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Pruebas
      POSTGRES_PASSWORD: Pruebas4321*
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data:  # Volumen para la base de datos
    driver: local
  jenkins_home:  # Volumen para Jenkins
    driver: local

networks:
  project_network:  # Red compartida entre los servicios
    driver: bridge
